// This file was auto-generated by ML.NET Model Builder. 

using System;
using AIProjectsIntecCSharpML.Model;

namespace AIProjectsIntecCSharpML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Open_ = 9131.81F,
                Market_Cap = 1.687104E+11F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual High with predicted High from sample data...\n\n");
            Console.WriteLine($"Open_: {sampleData.Open_}");
            Console.WriteLine($"Market_Cap: {sampleData.Market_Cap}");
            Console.WriteLine($"\n\nPredicted High: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
